### ISSUE TITLE
when 1.8.8.5?

### ISSUE THREAD

**Issue by iptory** [justinl99/mydockfinder-steam-free#1]
i really need the multi-monitor function

**Comment by jtlw99** [comment]
calmdown, 1.8.8.5 soon

**Comment by ghost** [comment]
![Screenshot 2022-07-11 223620](https://user-images.githubusercontent.com/100816109/180267928-d932d59c-ab74-436e-8e3e-4cfee3ec2ce5.png)
Thank you for the updates.
