### ISSUE TITLE
new versions?

### ISSUE THREAD

**Issue by teddtastic** [justinl99/mydockfinder-steam-free#2]
hey uh
could you keep the repo updated with the latest versions of the app?
1.8.9.2 is out i believe 
your latest release is 1.8.9
Thanks

**Comment by jtlw99** [comment]
Sorry but version 1.8.9.2 added a new feature that need Steam connection to verify the app, so u cant use the cr@ck
![image](https://user-images.githubusercontent.com/93564256/186124536-0fbdc4de-296f-449b-8e55-36e70f2efff8.png)
