### ISSUE TITLE
Trash icon is not set and can't be changed

### ISSUE THREAD

**Issue by hapatapa** [justinl99/mydockfinder-steam-free#3]
Your cr@ck is a bit broken, the trash icon is just empty... haven't you checked if it was okay before publishing?
![image](https://user-images.githubusercontent.com/68708992/211673766-e3d0eec4-4ae4-4a05-a9a1-2854398e333d.png)

**Comment by hapatapa** [comment]
Calendar is the same
![image](https://user-images.githubusercontent.com/68708992/211674788-77b7e930-6811-4eaa-9f43-e0af56e85c73.png)

**Comment by jtlw99** [comment]
### this is because i changed the icon of its. You can change the icons using this:
![Screenshot 1](https://user-images.githubusercontent.com/93564256/228848613-ae63de40-aeeb-4feb-b5e1-851889c3139a.png)
