### ISSUE TITLE
winui failed

### ISSUE THREAD

**Issue by 4toyota2supra** [justinl99/mydockfinder-steam-free#4]
when i launch it on win11 it says
![image](https://user-images.githubusercontent.com/89244602/229161879-9c295b67-0cb9-4337-9c94-634920e1c3cb.png)

**Comment by jtlw99** [comment]
what version?

**Comment by jtlw99** [comment]
It is a matter of not installing the [VC2019 runtime library](
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)
