### ISSUE TITLE
theming

### ISSUE THREAD

**Issue by teddtastic** [justinl99/mydockfinder-steam-free#7]
hey since this is  a cracked version, how can one apply the macOS theme of mydockfinder?
i don't know much about steam and stuff so please help me out

**Comment by jtlw99** [comment]
**i leave the theme files here: [Themes](https://github.com/justinl99/mydockfinder-steam-free/tree/main/Themes)**
You can choose one of them, go to MyDockFinder folder, find `themes` folder, replace items in `default` with items in the theme file you downloaded and done!
